### ISSUE TITLE
Savannas are ... Not

### ISSUE THREAD

**Issue by SilverKytten** [AOCAWOL/BYG#36]
This is not a Savanna, I'm not sure if it's a bug or just misnamed but I LOL'd.
![2020-05-22_18 20 12](https://user-images.githubusercontent.com/2188185/82715544-3006dd00-9c59-11ea-99d5-a0537018236d.png)

Savannas, for reference:
![image](https://user-images.githubusercontent.com/2188185/82715546-35fcbe00-9c59-11ea-8715-335197d13c9f.png)

**Comment by AOCAWOL** [comment]
I think another mod of yours is causing this, the Baobab Savanna does not look like this at all lol

**Comment by AOCAWOL** [comment]
[https://i.imgur.com/E8kCa7o.png](url)

As of version 0.4.0, the Baobab Savanna looks like this.

**Comment by SilverKytten** [comment]
This is a hilarious mod interaction, thank you for the clarity.

**Comment by AOCAWOL** [comment]
Lol no problem :)
